// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBFr1Mflwp1F80pnOjIB_ro6qBgTKhQLzc',
    appId: '1:381734049287:web:d51d36223044747893fca2',
    messagingSenderId: '381734049287',
    projectId: 'madecommercegit',
    authDomain: 'madecommercegit.firebaseapp.com',
    storageBucket: 'madecommercegit.firebasestorage.app',
    measurementId: 'G-YTWV1KCX1Z',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD8kiQJU-aL-_olJPU5bRUNT0J3lyEPEcU',
    appId: '1:381734049287:android:bbdcee4b999b024493fca2',
    messagingSenderId: '381734049287',
    projectId: 'madecommercegit',
    storageBucket: 'madecommercegit.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDTlmOtAUTLVB1SMCvgcQ2kUm-46rpG0Bg',
    appId: '1:381734049287:ios:2036ea344f73be8f93fca2',
    messagingSenderId: '381734049287',
    projectId: 'madecommercegit',
    storageBucket: 'madecommercegit.firebasestorage.app',
    iosBundleId: 'com.example.madEcommerce',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDTlmOtAUTLVB1SMCvgcQ2kUm-46rpG0Bg',
    appId: '1:381734049287:ios:2036ea344f73be8f93fca2',
    messagingSenderId: '381734049287',
    projectId: 'madecommercegit',
    storageBucket: 'madecommercegit.firebasestorage.app',
    iosBundleId: 'com.example.madEcommerce',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBFr1Mflwp1F80pnOjIB_ro6qBgTKhQLzc',
    appId: '1:381734049287:web:1631329d683c332693fca2',
    messagingSenderId: '381734049287',
    projectId: 'madecommercegit',
    authDomain: 'madecommercegit.firebaseapp.com',
    storageBucket: 'madecommercegit.firebasestorage.app',
    measurementId: 'G-BLRXPZQLR1',
  );

}